'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const productIds = ['romarin','thym','thym-rose','eucalyptus','chene','citronnier','lavande','lavande-papillon','tilleul','garrigue','coriandre','royal','pollen'];
for (const id of productIds) assert(html.includes('data-id="'+id+'"'), 'Produit absent : '+id);
assert(html.includes('212716014148'), 'Destinataire WhatsApp manquant');
assert(html.includes('BASE_PACK = 50'), 'Tarif de base manquant');
assert(html.includes('THYME_EXTRA = 5'), 'Supplément thym manquant');
assert(html.includes('ROYAL_EXTRA = 10'), 'Supplément gelée royale manquant');
assert(html.includes('ROYAL_SINGLE_PRICE = 25'), 'Prix individuel gelée royale manquant');
assert(html.includes('Pollen de montagne'), 'Pollen manquant');
assert(html.includes('honey5'), 'Cinquième choix manquant');
assert(html.includes('Logo historique NATUROMIEL'), 'Logo historique manquant');
assert(html.includes('const embeddedImages'), 'Visuels autonomes manquants');
assert(html.includes('og:image') && html.includes('naturomiel-og-1200x630.png'), 'Miniature Open Graph manquante');
assert(html.includes('twitter:card') && html.includes('summary_large_image'), 'Twitter Card manquante');
assert(html.includes('og:url'), 'URL partage social manquante');
assert(html.includes('lundi 12 octobre 2026'), 'Date de livraison manquante');
assert(html.includes('orderForOther') && html.includes('recipientName') && html.includes('recipientPhone'), 'Livraison pour autrui manquante');
assert(html.includes('Carte bancaire (lien Stripe sur demande)'), 'Paiement par carte Stripe manquant');
assert(!html.includes('Il n’est plus offert') && !html.includes('(non offert)'), 'Ancien texte pollen offert toujours présent');
assert(!html.includes('<h3>Pollen au choix</h3>'), 'Ancien encadré pollen non retiré');
assert(html.match(/form\.addEventListener\('submit'/g)?.length === 1, 'Double gestionnaire de validation');
assert(html.match(/window\.location\.assign\(url\)/g)?.length === 1, 'Double navigation WhatsApp');
assert(!html.includes('window.open('), 'Ouverture d’un second onglet WhatsApp détectée');
assert(html.includes('lastWhatsAppOpenedAt<20000'), 'Anti-doublon WhatsApp manquant');
console.log('PASS : 13 références, 5 choix, prix 50 + 5 + 10, unité 25 €, un seul envoi WhatsApp, livraison tiers, Stripe et métadonnées sociales.');
